### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danipolo**
Added bridge-utils

### CODE REVIEW

**Comment by tom472** [comment]
What is the need for the Plex section?

**Comment by danipolo** [comment]
I was doing it as root in first instance and it gave me some warnings when running compose. Just to clarify its not a "must" but I think it's easier to follow from a clean Ubuntu install. Nothing important but useful. The **bridge-utils it's a must**.

**Comment by tom472** [comment]
This should be being run as the "User" you normally run as - this way all the references to:
PUID
PGID
Are populated with the correct values.

I think I'll pass on adding the Plex section - (I'll keep my eye on the official Plex release and see if they add any steps) 

But thanks for the **bridge-utils** - info.

If you want the the credit for the Pull Request - update it to reflect just the addition of the bridge-utils.

If you don't necessarily care about the credit for the pull - then let me know and I'll just add that to the prerequisites section

Thanks again!

**Comment by tom472** [comment]
Closing this Pull Request - 
I added the **bridge-utils** to the Pre-Reqs -- 

Thanks
--Tom

**Pull request closed without merging**
