### PR TITLE
Switch to linuxserver/ombi

### PR DESCRIPTION
**Pull request by Ryanb58**

### CODE REVIEW

**Comment by tom472** [comment]
@Ryanb58 Why did you go right through and close this PR?
Was that by mistake / miss-click?

Can you tell me more about the `:shared` addition to the CouchPotato volume?
I see your comment about seeing mounts from the host machine but I'm not actually grasping the purpose.
I've never seen the `:shared` flag used before so I'll have to go look into it, feel free to hit me with a TLDR or point me to a good link about it.

Also - thanks for the heads-up about switching to the LinuxServer OMBI - I'll fire that up and give it a test run. Just curious - any 'major' reasons to make the switch? Updated more, newer version etc?

Thanks again for helping out the project.

**Comment by Ryanb58** [comment]
@tom472 I was thinking that upgradding ombi to 3.0 would be cool. But then I came across plex request... it just seems easier for the less technically savvy to use. Plus it is nice that they can manage their wants/needs inside of the plex app itself. 

I have forked your repo here: https://github.com/Ryanb58/mediabox/. Feel free to LMK what you think about them. I will work towards getting a stable build that I can merge back into this repo. However, if you want to keep ombi in your repo then it may diverge, as I forked it to do some custom stuff that meets my own needs. I don't want to clutter up your repo with excess apps if you don't want them. 

I do have a PR in my own repo for switching over to linusserver/ombi. LMK what you think. If you like it i'll do a PR for it here as well:
https://github.com/Ryanb58/mediabox/pull/3/files

`:shared` isn't really well documented right now, but without it mounted shares or mounted USB drives to the host will not show up in volumes.

**Comment by tom472** [comment]
@Ryanb58 - So are you going to try the LinuxServer Plex Requests container as a replacement for Ombi?
I'll probably just have both of them there and let people decide which they prefer, kind of like Sickrage v Sonarr and CouchPotato v Radarr.
Looking at the releases of Ombi it does look like the LinuxServer image is more current - so I'll most likely switch to that - thanks for the heads up.
I have been getting asked to add in Headphones so I'll be adding that probably this weekend.

Thanks again for the suggestions / recommendations.

Also for the `:shared` flag - would that be useful for more than just CouchPotato?
Just wondering.

**Comment by tom472** [comment]
Made the switch to LinuxServer.io version of Ombi 

@Ryanb58 Thanks again for the heads-up on that.

**Pull request closed without merging**
