### PR TITLE
Added NZB Support

### PR DESCRIPTION
**Pull request by kspillane**
## Added NZBGet

Added support to run NZBGet container for those interested in using usenet for getting their things.  I chose NZBGet because:  

* I already use it
* It has better performance at higher speeds
* It is lightweight and simple to use

However, I am open to using something else, but I would ask that you try it out if you haven't used it.

## Changes

* Added entry for NZBGet in compose file
* Added line to create nzbget directory
* Changed verbiage on deluge dameon user/pass prompt
* Added code to load delugedaemon user and pass as webui credentials for NZBGet
* Added warning that configuring httpd permissions would take longer
* Changed mv index.html to cp

## Caveats

* Tested ok! NZBGet comes up, did not configure for use, though, no real need.
* Did not add configuration instructions to html page, would like to update the html in next project

I blew out the commits from the 12th and re-pulled from the upstream master. Only the commits from the 15th are accurate.

### CODE REVIEW

**Comment by tom472** [comment]
@kspillane Hey - can I ask you to resubmit this PR?

Base it off the latest master with the new VPN choice section and no `.env` file.
Also, and this is just my OCD, can you put the NZBGet section in the compose where it should land based on alphabetical order.

Let me know - 

Thanks
--Tom

**Comment by kspillane** [comment]
I did a PR from my master to make it even. I will redo the compose file later and submit a new PR with the new commits. It has been a lazy weekend...

**Comment by kspillane** [comment]
Moved NZBGet to alphabetized position in docker-compose file. See commit f25e918.

**Comment by tom472** [comment]
Thanks @kspillane

**Pull request merged**
